version: "3.9"

services:
    # ========================
    # PHP (Laravel backend)
    # ========================
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        environment:
            APP_ENV: production
            APP_DEBUG: false
            APP_KEY: base64:chave_gerada_aqui
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: csv_importer
            DB_USERNAME: laravel
            DB_PASSWORD: secret
            QUEUE_CONNECTION: database
            CACHE_DRIVER: redis
            SESSION_DRIVER: redis
            REDIS_HOST: redis
            REDIS_PORT: 6379
        volumes:
            - storage_data:/var/www/storage
        depends_on:
            - mysql
            - redis

    # ========================
    # Nginx (servidor web)
    # ========================
    nginx:
        image: nginx:1.25
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - storage_data:/var/www/storage
        depends_on:
            - app

    # ========================
    # MySQL
    # ========================
    mysql:
        image: mysql:8
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: csv_importer
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    # ========================
    # Redis
    # ========================
    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"

volumes:
    mysql_data:
    storage_data:
