services:
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootsecret123}
            MYSQL_DATABASE: csv_importer
            MYSQL_USER: laravel
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-laravelsecret123}
            MYSQL_ROOT_HOST: '%'
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network
        command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
            interval: 10s
            start_period: 40s
        restart: unless-stopped

    redis:
        image: redis:7-alpine
        volumes:
            - redis_data:/data
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            timeout: 10s
            retries: 5
            interval: 10s
            start_period: 30s
        restart: unless-stopped

    laravel_app:
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - "9000:9000"
        environment:
            APP_NAME: "CSV Contact Importer"
            APP_ENV: production
            APP_DEBUG: "false"
            APP_URL: ${APP_URL:-http://localhost:8080}
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: csv_importer
            DB_USERNAME: laravel
            DB_PASSWORD: ${MYSQL_PASSWORD:-laravelsecret123}
            QUEUE_CONNECTION: database
            CACHE_DRIVER: redis
            SESSION_DRIVER: redis
            REDIS_HOST: redis
            REDIS_PORT: 6379
            BROADCAST_DRIVER: log
            LOG_CHANNEL: stack
            LOG_LEVEL: error
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
        volumes:
            - ./:/var/www
        networks:
            - app-network
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "php", "artisan", "tinker", "--execute=echo 'OK';"]
            timeout: 10s
            retries: 5
            interval: 30s
            start_period: 60s

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/default:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/public:ro
            - storage_data:/var/www/storage:ro
        depends_on:
            laravel_app:
                condition: service_healthy
        networks:
            - app-network
        restart: unless-stopped

volumes:
    mysql_data:
        driver: local
    redis_data:
        driver: local

networks:
    app-network:
        driver: bridge
