version: '3.9'

services:
    # PHP-FPM para Laravel
    laravel_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            - ./src:/var/www/html
            - ./storage:/var/www/html/storage
        networks:
            - app-network
        depends_on:
            - mysql
            - redis

    # Nginx para servir o Laravel
    nginx:
        image: nginx:1.25
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./nginx:/etc/nginx
            - ./src:/var/www/html
        networks:
            - app-network
        depends_on:
            - laravel_app

    # Banco de dados MySQL
    mysql:
        image: mysql:8
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel_password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network

    # Redis
    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - app-network

# Volumes persistentes
volumes:
    mysql_data:

# Rede interna
networks:
    app-network:
        driver: bridge
